### ISSUE TITLE
Сolor palette doesn't appear in case the side menu is not minimized

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/grapesjs-addon#12]
Related issue https://github.com/cuba-platform/emailtemplate-addon/issues/31

**Comment by zhenyazb** [comment]
The following cases are reproduced for the email-template-addon with not minimized side menu and small screens.
1. Color palette is cropped on the left and the scroll bar can be moved only to the righ. 
![pic1](https://user-images.githubusercontent.com/45868670/77146952-af373380-6aa5-11ea-87f4-c1477c6091e4.png)
2. Bottom scroll bar does not appear in case color palette is called from the sub-section.
![pic2](https://user-images.githubusercontent.com/45868670/77147362-7b104280-6aa6-11ea-9898-3c2668e0633a.png)

**Comment by konyashkina** [comment]
Tested on 
CUBA Platform version: 7.2.15
CUBA Studio plugin version: 15.6-211
GrapesJs v.0.5.3
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)
