### ISSUE TITLE
User can't edit a Video element

### ISSUE THREAD

**Issue by dmakagonova** [cuba-platform/grapesjs-addon#6]
### Environment

- Platform version: 7.1 
- Addon version: 0.3-SNAPSHOT 

1. Run demo project
2. Click Application -> Html screen
3. Move Video to the canvas
4. Open Video editor / double click or one click on a Video 

Expected result: Video editor is opened
Actual result: Video editor is NOT opened

**Comment by zaharchenko-evgeny** [comment]
Video element will be removed in 1.4.x version
